### ISSUE TITLE
google-auth-library problem

### ISSUE THREAD

**Issue by wewryman** [Aerolab/rooms#10]
Hi, since yesterday i have this problem, nothing changed on my side, was working fine till now.

```
> rooms@1.0.0 start
> NODE_ENV=production node server.js

API available at port 8184
/home/virtual/rooms-new/rooms-bak/node_modules/google-auth-library/lib/transporters.js:85
        err = new Error(body.error.errors.map(
              ^

Error: Internal error encountered.
    at Request._callback (/home/virtual/rooms-new/rooms-bak/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/home/virtual/rooms-new/rooms-bak/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/home/virtual/rooms-new/rooms-bak/node_modules/request/request.js:1161:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/home/virtual/rooms-new/rooms-bak/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 500,
  errors: [
    {
      message: 'Internal error encountered.',
      domain: 'global',
      reason: 'backendError'
    }
  ]
}

```

**Comment by wewryman** [comment]
started working without doing anything after few days
