### ISSUE TITLE
Problem with JWT / GoogleToken

### ISSUE THREAD

**Issue by mdzidic** [Aerolab/rooms#8]
Hello,

I'm trying to run Docker version of the rooms app but without success.

When I try to open http://127.0.0.1:3000/lounge or http://127.0.0.1:3000/api/rooms/lounge it throws this error:
```
> rooms@1.0.0 start /usr/src/app
> NODE_ENV=production node server.js

API available at port 3000
(node:20) UnhandledPromiseRejectionWarning: Error: No key or keyFile set.
    at GoogleToken.getToken (/usr/src/app/node_modules/gtoken/lib/index.js:52:16)
    at /usr/src/app/node_modules/google-auth-library/lib/auth/jwtclient.js:137:21
    at JWT._createGToken (/usr/src/app/node_modules/google-auth-library/lib/auth/jwtclient.js:226:12)
    at JWT.refreshToken_ (/usr/src/app/node_modules/google-auth-library/lib/auth/jwtclient.js:133:15)
    at JWT.OAuth2Client.getRequestMetadata (/usr/src/app/node_modules/google-auth-library/lib/auth/oauth2client.js:284:15)
    at JWT.getRequestMetadata (/usr/src/app/node_modules/google-auth-library/lib/auth/jwtclient.js:79:52)
    at JWT.OAuth2Client.request (/usr/src/app/node_modules/google-auth-library/lib/auth/oauth2client.js:379:15)
    at Object.createAPIRequest [as default] (/usr/src/app/node_modules/googleapis/lib/apirequest.js:151:26)
    at Object.list (/usr/src/app/node_modules/googleapis/apis/calendar/v3.js:1042:40)
    at Promise (/usr/src/app/api/calendar.js:65:21)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RobertoGonzalez** [comment]
You need to add the Google Calendar API Key, which is kind of annoying to set up. There's some instructions in the readme, though setting up the permissions will take a bit of trial and error.
